### ISSUE TITLE
"Ratings" only captures the first digit

### ISSUE THREAD

**Issue by dastratman** [joonaspaakko/audible-library-extractor#147]
The number of ratings only captures the first digit, e.g. 4,150 actual ratings = 4 ALE ratings.

![2024-05-06 19_24_51-Window](https://github.com/joonaspaakko/audible-library-extractor/assets/697670/cce9d759-e8ec-4098-9122-e11ae526bf0f)
![2024-05-06 19_24_43-Window](https://github.com/joonaspaakko/audible-library-extractor/assets/697670/cdde00be-4c1f-45a7-87e8-a0fa9422b18e)

**Comment by joonaspaakko** [comment]
The number of ratings is fixed in dev draft, if you don't mind installing that:

1. Download this [0.2.11 dev draft](https://github.com/joonaspaakko/audible-library-extractor/raw/master/audible-library-extractor-0.2.11.zip) zip file. 
2. Go to the address: `chrome:extensions` or open: Window > Extensions 
3. Turn on the developer mode from the top right 
4. Drag the downloaded .zip file in the browser. 

Installation done. 

If you have hundreds of books, you should probably import your old data so that you can do the quicker partial extraction to update number of ratings: 

1. [Export raw data from current installation](https://joonaspaakko.gitbook.io/audible-library-extractor/gallery/import-export-data)
2. Install development draft
3. Import raw data 
4. Click the big bue button.

**Comment by joonaspaakko** [comment]
#134

**Comment by dastratman** [comment]
Excellent, thank you!
