### ISSUE TITLE
Unable to use wallpaper extractor 

### ISSUE THREAD

**Issue by demoran23** [joonaspaakko/audible-library-extractor#69]
With the end of the year coming up, I gave the wallpaper generator a shot and I got a null reference exception and a blank page. The thing is, even when I pull down the latest code and use that, I still get the same thing, and I'm at a loss as to why.

[Audible Library Extractor Data.zip](https://github.com/joonaspaakko/audible-library-extractor/files/7730841/Audible.Library.Extractor.Data.zip)

**Comment by demoran23** [comment]
Here's what I see when I open the wallpaper extractor:

![image](https://user-images.githubusercontent.com/6959036/146484900-861f2263-1de2-4a60-8254-e1eaf34756d9.png)

I've tried clearing localstorage, tried incognito, and tried disabling all of my other extensions.  It looks like that div isn't mounted on the dom.

**Comment by joonaspaakko** [comment]
@demoran23, I can't seem to find anything wrong with it. The weirdest thing about what you've shared so far is the last screenshot and the empty comment. In Vue, this empty comment (usually) means that the spot is reserved for an element that is currently "hidden".

Now the thing about that is, there should be a static element where the empty comment is `<div id="wallpaper-creator"></div>`. It's the root element that comes from the HTML file and is not created (or removed) programmatically.

https://github.com/joonaspaakko/audible-library-extractor/blob/07da0bce8e4765e9d7f0b8c877537ee2cb5dc918/src/wallpaper-creator/wallpaper-creator.html#L16

So then, I think the first question is... Why is it not there?

Since you have access to the project source, I'd like you to try removing the two `script` lines (`17, 18`), just to confirm if the app's own code is somehow malfunctioning and removing that static element. 

> Where to go from there, I don't know.

**Comment by demoran23** [comment]
With the js commented out:

![image](https://user-images.githubusercontent.com/6959036/146601622-c90b64d8-e99b-48cb-9733-7a75de6f2522.png)

This happens regardless of whether the polyfill is commented or not.

**Comment by joonaspaakko** [comment]
So it is something in the wallpaper-creator.js I guess. I was kinda hoping something else. 

I can't remember if you said so, but did you download the release build or just clone the repo? Because if you try the release build v.0.2.7 in Chrome with your data and it doesn't work... And I've tried the same release build in Chrome with your data but it works... How could that be? The only variable left would be perhaps the browser version or maybe the installation method... If we're reaching.

I'm kinda leaning towards you perhaps cloning or pulling the repo and tripping on some dev quirk. Like maybe you didnt do `npm install` or something. That's the only way I can imagine it behaving differently from what I'm seeing on my end.

**Comment by demoran23** [comment]
Unfortunately I first hit my head against this using the version from the chrome webstore.  So it was the release build.  And I'm doing by tests from the dist folder after building locally.  I've got the latest version of Chrome (Version 96.0.4664.110 (Official Build) (64-bit)).

Remember, the way I'm getting to the wallpaper creator page in the first place is by going to Audible, clicking on the link to open the gallery, and then clicking on the wallpaper creator button, so if it failed to build locally, then I wouldn't be able to get that far in the first place, which would mean that we'd never see the null reference exception.

Let me know if you're interested in a screen share sometime; we could try to troubleshoot it together.  I wonder if I'm the only one with this issue.

**Comment by joonaspaakko** [comment]
I didn't mean to suggest the build failed (entirely). Something very specific to the wallpaper creator could've broken (or something), like the thing with saving the standalone gallery. At the very least it has way more things that could go wrong than us both using the release build and it behaving differently.

I've tried the release build on a couple different versions of Firefox and Chrome on Mac and Windows with your data. I'm using the same chrome version. It should be the same exact scenario.

I'll contact you about screen sharing or something if I get any ideas, but I don't have any right now <small>(aside from maybe removing components one by one until it works)</small>.

> I've not had any other complaints, but I have no idea if anyone else other than me has used it succesfully.
