### ISSUE TITLE
I just see a blank screen

### ISSUE THREAD

**Issue by michaelschwob** [joonaspaakko/audible-library-extractor#77]
Hello. I love the idea of this tool. However, upon execution, I just see a blank screen. My repository and associated site are below:

https://github.com/michaelschwob/my-audible-library

https://michaelschwob.github.io/my-audible-library/

**Comment by joonaspaakko** [comment]
It's looking for some important files from the folder called `data` and it's missing entirely in your repository. It should be in the folder root after unpacking the zip file in the current version 0.2.8 (**see the screenshot below**).

So the question is... is it possible that the `data` folder got misplaced after you saved the zip file and unpacked it or was it never there? Some "program" error could've caused it to be excluded, but I'm hoping that's not the case as it will be difficult to debug.

<img width="317" alt="image" src="https://user-images.githubusercontent.com/1164476/152616051-2f8f4c7d-a9e9-4ad6-a2c7-daa40eeb2c02.png">

**Comment by michaelschwob** [comment]
Thanks for the quick reply. I see the issue. When I attempted to upload my data folder, I received an error that says "Yowza, that’s a lot of files. Try again with fewer than 100 files." Any tips on how I can upload the data folder altogether within having the upload all the files in batches?

**Comment by joonaspaakko** [comment]
My best guess is you tried to upload through the website. The easiest way would be using github desktop. 

Upload [instructions](https://joonaspaakko.gitbook.io/audible-library-extractor/sharing/uploading-to-github) from scratch. 

Though since you already have the repository made, you probably have to (**should**) use the desktop client to [clone](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/adding-and-cloning-repositories/cloning-and-forking-repositories-from-github-desktop) (download) the repository first then follow these [instructions](https://joonaspaakko.gitbook.io/audible-library-extractor/sharing/uploading-to-github/updating-gallery-in-github).

**Comment by michaelschwob** [comment]
Okay, thank you for the suggestion!
